### ISSUE TITLE
Add a contributor bot in readme

### ISSUE THREAD

**Issue by nirala96** [nirala96/open_source_start#76]
add the contributor bot in the readme that will automatically update the contributors in the readme

**Comment by lbaweja1999** [comment]
@nirala96 I would like to work on it. Please assign this issue to me.

**Comment by nirala96** [comment]
Sure @lbaweja1999 go for it

**Comment by lbaweja1999** [comment]
Thanks @nirala96

**Comment by lbaweja1999** [comment]
@nirala96 what would you prefer a CLI or GUI for the bot?

**Comment by lbaweja1999** [comment]
@nirala96 please tell?

**Comment by nirala96** [comment]
@lbaweja1999 want a bot that shows the total contributors in the readme

go through this - https://github.com/all-contributors/all-contributors/blob/master/README.md

**Comment by lbaweja1999** [comment]
> @lbaweja1999 want a bot that shows the total contributors in the readme
> 
> go through this - https://github.com/all-contributors/all-contributors/blob/master/README.md

@nirala96  I had gone through this only. In this we have to options to configure it in any repo i.e 1. Directly installing the third-party app inside the repo( in this we have to give all the permissions to the app) and 2. Using CLI.

Please check these out for reference:-
1. App - https://allcontributors.org/docs/en/bot/overview
2. CLI - https://allcontributors.org/docs/en/cli/overview

**Comment by nirala96** [comment]
CLI would be great

**Comment by lbaweja1999** [comment]
> CLI would be great
> 

Okay cool will do that

**Comment by nirala96** [comment]
Nice work @lbaweja1999

**Comment by lbaweja1999** [comment]
@nirala96 Please add the label "hacktoberfest-accepted" to the pull request, so that it marks my first valid pull request 😀.
